[package]
name = "BlinkSync"
version = "0.1.1"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features = [ "json" ] }
clap = "4.2.2"
http = "0.2.9"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.106"
urlencoding = "2.1.3"
chrono = "0.4.30"
