[package]
name = "BlinkSync"
version = "0.1.0"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features = [ "json" ] }
clap = "4.2.1"
http = "0.2.9"
serde = "1.0.159"
serde_json = "1.0.95"
urlencoding = "2.1.2"
serde_derive = "1.0.159"
chrono = "0.4.24"
